# Generated by Django 5.2.4 on 2026-07-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.IntegerField()),
                ('year', models.CharField(max_length=50)),
                ('attendance', models.FloatField()),
                ('internal_marks', models.FloatField()),
                ('assignment_marks', models.FloatField()),
                ('semester1_marks', models.FloatField()),
                ('semester2_marks', models.FloatField()),
            ],
        ),
    ]
