# Generated by Django 5.2.4 on 2026-07-13 16:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='semester1_marks',
            new_name='semester1_cgpa',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='semester2_marks',
            new_name='semester2_cgpa',
        ),
        migrations.AddField(
            model_name='student',
            name='subject_type',
            field=models.CharField(choices=[('major', 'Major'), ('minor', 'Minor')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
