# Generated by Django 5.2.4 on 2026-07-14 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_semester1_marks_student_semester1_cgpa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject_type', models.CharField(choices=[('Major', 'Major'), ('Minor', 'Minor')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='assignment_marks',
        ),
        migrations.RemoveField(
            model_name='student',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='student',
            name='internal_marks',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester1_cgpa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester2_cgpa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subject_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_marks', models.IntegerField()),
                ('assignment_marks', models.IntegerField()),
                ('practical_marks', models.IntegerField()),
                ('final_exam_marks', models.IntegerField()),
                ('attendance', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject')),
            ],
        ),
    ]
