# Generated by Django 5.2.4 on 2026-07-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_subject_remove_student_assignment_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='semester',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='semester_attendance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('FY', 'First Year'), ('SY', 'Second Year'), ('TY', 'Third Year'), ('MSC1', 'MSc Part 1'), ('MSC2', 'MSc Part 2')], default='FY', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('MAJOR', 'Major'), ('MINOR', 'Minor')], max_length=50),
        ),
    ]
