# Generated by Django 5.2.4 on 2026-07-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_marks_semester_marks_semester_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='semester_attendance',
        ),
        migrations.AddField(
            model_name='student',
            name='semester_attendance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
