# Generated by Django 5.2.4 on 2026-07-14 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_marks_semester_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester_attendance',
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('attendance_percentage', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
