# Generated by Django 5.2.4 on 2026-08-05 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_marks_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='unit_1_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marks',
            name='unit_2_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marks',
            name='unit_3_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='assignment_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marks',
            name='final_exam_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marks',
            name='internal_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marks',
            name='practical_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
