# Generated by Django 5.2.4 on 2026-08-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_marks_unit_1_marks_marks_unit_2_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='unit_4_marks',
            field=models.IntegerField(default=0),
        ),
    ]
