# Generated by Django 5.2.4 on 2026-08-18 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_marks_unit_4_marks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together={('student', 'subject', 'semester')},
        ),
        migrations.AddField(
            model_name='marks',
            name='semester_exam_marks',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='marks',
            name='assignment_marks',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='internal_marks',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='practical_marks',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='marks',
            name='unit_1_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='marks',
            name='unit_2_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='marks',
            name='unit_3_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='marks',
            name='unit_4_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('FY', 'B.Sc First Year'), ('SY', 'B.Sc Second Year'), ('TY', 'B.Sc Third Year'), ('MSC1', 'M.Sc Part 1'), ('MSC2', 'M.Sc Part 2')], default='FY', max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(default='THEORY', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'semester')},
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Coding', 'Coding / Hackathon'), ('Sports', 'Sports'), ('Academic', 'Academic Excellence'), ('Cultural', 'Cultural / Extra-Curricular'), ('Research', 'Paper Publication / Research')], default='Coding', max_length=50)),
                ('description', models.TextField()),
                ('date_awarded', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TEACHER', 'Teacher / Faculty'), ('STUDENT', 'Student')], default='STUDENT', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='marks',
            name='final_exam_marks',
        ),
    ]
