# Generated by Django 5.2.4 on 2026-08-18 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_marks_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attended_lectures',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_lectures',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marks',
            name='grade',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='marks',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='marks',
            name='result_status',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='marks',
            name='strongest_unit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='marks',
            name='total_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='marks',
            name='total_unit_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='marks',
            name='weakest_unit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='max_marks',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='students.student'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='assignment_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='internal_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='practical_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='semester_exam_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='unit_1_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='unit_2_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='unit_3_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='unit_4_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('THEORY', 'Theory Only'), ('PRACTICAL', 'Practical Only'), ('BOTH', 'Theory & Practical Combined')], default='THEORY', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('STUDENT', 'Student')], default='STUDENT', max_length=10),
        ),
    ]
