# Generated by Django 5.2.4 on 2026-08-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='total_unit_marks',
            new_name='total_internal_marks',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'semester')},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('Coding', 'Coding / Hackathon'), ('Sports', 'Sports'), ('Academic', 'Academic Excellence'), ('Cultural', 'Cultural / Extra-Curricular'), ('Research', 'Paper Publication / Research')], default='Coding', max_length=50),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='marks',
            name='semester_exam_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together={('student', 'subject', 'semester')},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='attended_lectures',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_eligible',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='total_lectures',
        ),
    ]
