# Generated by Django 5.2.4 on 2026-08-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_rename_total_unit_marks_marks_total_internal_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='max_marks',
        ),
        migrations.AddField(
            model_name='subject',
            name='max_assignment_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='subject',
            name='max_internal_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='subject',
            name='max_practical_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='subject',
            name='max_theory_marks',
            field=models.FloatField(default=50.0),
        ),
        migrations.AlterField(
            model_name='marks',
            name='semester_exam_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='strongest_unit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='marks',
            name='total_internal_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='total_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='weakest_unit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('THEORY', 'Theory Only'), ('PRACTICAL', 'Practical Only'), ('BOTH', 'Theory & Practical / Combined')], default='THEORY', max_length=15),
        ),
    ]
