# Generated by Django 5.2.4 on 2026-08-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_remove_subject_max_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='date_awarded',
        ),
        migrations.AddField(
            model_name='achievement',
            name='date_achieved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='presentation_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='max_presentation_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='subject',
            name='total_max_marks',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='subject',
            name='unit_1_max',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='subject',
            name='unit_2_max',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='subject',
            name='unit_3_max',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='subject',
            name='unit_4_max',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(default='Academic', max_length=100),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='max_theory_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(default='Theory + Practical', max_length=50),
        ),
    ]
