# Generated by Django 5.2.4 on 2026-08-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_remove_achievement_date_awarded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='max_assignment_marks',
            field=models.FloatField(default=10.0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='max_internal_marks',
            field=models.FloatField(default=20.0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='max_practical_marks',
            field=models.FloatField(default=50.0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='max_presentation_marks',
            field=models.FloatField(default=10.0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='max_theory_marks',
            field=models.FloatField(default=50.0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(default='THEORY', max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='total_max_marks',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='unit_1_max',
            field=models.FloatField(default=12.5),
        ),
        migrations.AlterField(
            model_name='subject',
            name='unit_2_max',
            field=models.FloatField(default=12.5),
        ),
        migrations.AlterField(
            model_name='subject',
            name='unit_3_max',
            field=models.FloatField(default=12.5),
        ),
        migrations.AlterField(
            model_name='subject',
            name='unit_4_max',
            field=models.FloatField(default=12.5),
        ),
    ]
