# Generated by Django 5.2.4 on 2026-08-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_subject_max_assignment_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='max_theory_marks',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='unit_1_max',
            field=models.FloatField(default=25.0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='unit_2_max',
            field=models.FloatField(default=25.0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='unit_3_max',
            field=models.FloatField(default=25.0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='unit_4_max',
            field=models.FloatField(default=25.0),
        ),
    ]
