# Generated by Django 5.2.4 on 2026-08-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_alter_subject_max_assignment_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='classes_attended',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_classes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='part',
            field=models.CharField(choices=[('PART1', 'Part I'), ('PART2', 'Part II'), ('FY', 'First Year'), ('SY', 'Second Year'), ('TY', 'Third Year')], default='FY', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='programme',
            field=models.CharField(choices=[('FMCS', 'M.Sc. Computer Science (FMCS)'), ('SMCS', 'M.Sc. Computer Science (SMCS)'), ('BSC', 'B.Sc. Computer Science')], default='BSC', max_length=50),
        ),
    ]
