# Generated by Django 5.2.4 on 2026-08-21 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_attendance_classes_attended_attendance_total_classes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(default=1)),
                ('total_classes', models.IntegerField(default=0)),
                ('classes_attended', models.IntegerField(default=0)),
                ('attendance_percentage', models.FloatField(default=0.0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_attendances', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject')),
            ],
            options={
                'unique_together': {('student', 'subject', 'semester')},
            },
        ),
    ]
