# Generated by Django 5.2.4 on 2026-08-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_subjectattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectattendance',
            name='practical_attended',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subjectattendance',
            name='practical_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='subjectattendance',
            name='practical_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subjectattendance',
            name='theory_attended',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subjectattendance',
            name='theory_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='subjectattendance',
            name='theory_total',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
