# Generated by Django 5.2.4 on 2026-08-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_subjectattendance_practical_attended_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectattendance',
            name='attendance_percentage',
        ),
        migrations.RemoveField(
            model_name='subjectattendance',
            name='classes_attended',
        ),
        migrations.RemoveField(
            model_name='subjectattendance',
            name='practical_percentage',
        ),
        migrations.RemoveField(
            model_name='subjectattendance',
            name='theory_percentage',
        ),
        migrations.RemoveField(
            model_name='subjectattendance',
            name='total_classes',
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='Student', max_length=100),
        ),
    ]
