# Generated by Django 5.2.4 on 2026-08-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_remove_subjectattendance_attendance_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='student',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='college_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roll_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
