# Generated by Django 5.2.4 on 2026-08-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_remove_userprofile_student_userprofile_college_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='CS Department teacher email allowed to register', max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_registered', models.BooleanField(default=False)),
            ],
        ),
    ]
