# Generated by Django 5.2.4 on 2026-08-26 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_allowedteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='students.student'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('SPORTS', 'Sports'), ('ACADEMIC', 'Academic'), ('CULTURAL', 'Cultural'), ('OTHER', 'Other')], default='ACADEMIC', max_length=100),
        ),
    ]
