# Generated by Django 5.2.4 on 2026-08-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_userprofile_student_alter_achievement_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedteacher',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='allowedteacher',
            name='name',
            field=models.CharField(blank=True, help_text='e.g. Prof. Alan Turing', max_length=100),
        ),
    ]
