# Generated by Django 5.2.4 on 2026-08-27 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_alter_allowedteacher_email_alter_allowedteacher_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedExcelBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('year', models.CharField(choices=[('FY', 'B.Sc First Year'), ('SY', 'B.Sc Second Year'), ('TY', 'B.Sc Third Year'), ('MSC1', 'M.Sc Part 1'), ('MSC2', 'M.Sc Part 2')], default='FY', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
