# Generated by Django 5.2.4 on 2026-08-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_excelbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelbatch',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='excel_batches/'),
        ),
        migrations.AddField(
            model_name='uploadedexcelbatch',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='excel_uploads/'),
        ),
    ]
