# Generated by Django 5.2.4 on 2026-08-29 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_excelbatch_file_uploadedexcelbatch_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='excelbatch',
            name='record_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='excelbatch',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marks',
            name='excel_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_batch', to='students.excelbatch'),
        ),
        migrations.AddField(
            model_name='student',
            name='created_in_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_students', to='students.excelbatch'),
        ),
        migrations.AddField(
            model_name='subjectattendance',
            name='excel_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_batch', to='students.excelbatch'),
        ),
    ]
