# Generated by Django 5.2.4 on 2026-08-29 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0028_excelbatch_record_count_excelbatch_uploaded_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedExcelBatch',
        ),
    ]
