# Generated by Django 5.2.4 on 2026-09-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_delete_uploadedexcelbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedteacher',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
