# Generated by Django 5.2.4 on 2026-09-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0032_alter_marks_result_status_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='grade',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
