# Generated by Django 5.2.4 on 2026-09-11 17:19

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0033_alter_marks_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelbatch',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=students.models.get_pure_filename),
        ),
    ]
